In [2]:
import numpy as np

### Numpy Array Operations

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print('Basic slicing', arr[2:8])
print('with step',arr[1:8:2])
print('Negative indexing', arr[-2])

Basic slicing [3 4 5 6 7 8]
with step [2 4 6 8]
Negative indexing 9


In [5]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print('specific element',arr_2d[2,1])
print('entire row', arr_2d[2])
print('entire colum', arr_2d[:,0])

specific element 8
entire row [7 8 9]
entire colum [1 4 7]


### Sorting

In [6]:
unsorted = np.array([4,7,1,2,9,4,3,5,2,0])
print('sorted array', np.sort(unsorted))

sorted array [0 1 2 2 3 4 4 5 7 9]


In [7]:
arr_2d_unsorted = np.array([[3,1],[1,2],[3,4]])
print('sorted 2D array by colum', np.sort(arr_2d_unsorted, axis=1))

sorted 2D array by colum [[1 3]
 [1 2]
 [3 4]]


In [17]:
arr_2d_unsorted = np.array([[3,1],[1,2],[2,4]])
print('sorted 2D array by colum', np.sort(arr_2d_unsorted, axis=0))

sorted 2D array by colum [[1 1]
 [2 2]
 [3 4]]


### Filter

In [10]:
number = np.array([1,2,3,4,5,6,7,8,9])
even_number = number[number % 2 == 0]
print('Even numbers',even_number)

Even numbers [2 4 6 8]


### Filter with mask

In [17]:
number = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
mask = number > 5
print('number greater than 5',number[mask])

number greater than 5 [ 6  7  8  9 10 11 12 13]


### Fancy indexing vs np.where()

In [19]:
indices = [0,2,4,9]
print(number[indices])

[ 1  3  5 10]


In [22]:
where_result = np.where(number > 5)
print(where_result)
print('Np where', number[where_result])

(array([ 5,  6,  7,  8,  9, 10, 11, 12]),)
Np where [ 6  7  8  9 10 11 12 13]


In [26]:
condition_array = np.where(number >5, number*2, number )
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20 22 24 26]


In [38]:
condition_array = np.where(number >5, "true", "false" )
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true' 'true' 'true' 'true']


In [37]:
if number > 5:
    number*2

else:
    number = number

print(number)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [39]:
number = np.array([1,2,3,4,5,6,7])
condition_array = np.where(number>3,number*2,number)
print(condition_array)

[ 1  2  3  8 10 12 14]


### Adding and removing data

In [40]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2
print(combined)

[5 7 9]


In [41]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibilty

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print("Compatibility shapes", b.shape == c.shape)

Compatibility shapes True


In [11]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
#print(original)
print(with_new_row)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
original = np.array([[1,2],[3,4]])
new_col = np.array([[7],[8]])

with_new_col = np.hstack((original,new_col))
print('with new colum',with_new_col)

with new colum [[1 2 7]
 [3 4 8]]


In [16]:
arr =np.array([1,2,3,4,5,6,7])
deleted = np.delete(arr,0)
print('Array after deletion',deleted)


Array after deletion [2 3 4 5 6 7]
