In [9]:
!pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [10]:
import numpy as np

In [2]:
print(np.__version__)

2.5.1


### Creating Arrays

In [3]:
arr_1d = np.array([1,2,3,4,5,6])
print("1D array :", arr_1d)

1D array : [1 2 3 4 5 6]


In [29]:
arr_2d = np.array ([[1,2,3], [5,6,7]])
print("2d array:\n",arr_2d)

2d array:
 [[1 2 3]
 [5 6 7]]


### List vs Numpy Array

In [5]:
list = [1,2,3]
print('python list multiplication',list*2)

python list multiplication [1, 2, 3, 1, 2, 3]


In [9]:
array = np.array([1,2,3]) # element wise multiplication
print("python array multiplication",array * 2)

python array multiplication [2 4 6]


In [ ]:
array = np.array([1,2,3]) 
print("python array square",array ** 2)

python array square [1 4 9]


In [13]:
import time
start = time.time()
list = [i*2 for i in range(1000000)]
print("\n list operation time:", time.time()- start)





 list operation time: 0.10088300704956055


In [14]:
start = time.time()
array = np.arange(1000000)*2
print("\n numpy operation time:",time.time()- start)



 numpy operation time: 0.008611440658569336


### Creating array from scratch

In [20]:
Zeros = np.zeros((3,4))
print('zeros array:\n', Zeros)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
ones = np.ones((3,3))
print('ones array:\n',ones)

ones array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [23]:
full = np.full((2,2), 5)
print('full array:\n',full)

full array:
 [[5 5]
 [5 5]]


In [24]:
random = np.random.random((2,3))
print("random array:\n",random)

random array:
 [[0.78437084 0.10259663 0.29900146]
 [0.89267564 0.99450612 0.57257731]]


In [26]:
sequence = np.arange(0,10,3)
print("sequence array:\n",sequence)

sequence array:
 [0 3 6 9]


### Vector,Matrix and Tensor

In [4]:
vector = np.array([1,2,3])
print("Vector:", vector)

Vector: [1 2 3]


In [13]:
Matrix =np.array([[1,2,3,],
                  [4,5,6]])
print("Matrix :",Matrix)

Matrix : [[1 2 3]
 [4 5 6]]


In [14]:
Tensor = np.array([[[1,2,],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor :",Tensor)

Tensor : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [19]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape",arr.shape)
print("Dimension", arr.ndim)
print("size",arr.size)
print("Dtype",arr.dtype)
print("item size:",arr.itemsize)

shape (2, 3)
Dimension 2
size 6
Dtype int64
item size: 8


### Array Reshaping

In [ ]:
arr = np.arange(12)
print('original array', arr)



original array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [35]:
reshaped = arr.reshape((3,4))
print(" Reshape array:\n", reshaped)

 Reshape array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
flattened = reshaped.flatten()
print("flattened array", flattened)

flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [29]:
 # Ravel(return view,instead of copy)
raveled = reshaped.ravel()
print("raveled array",raveled)

raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [32]:
#Transpose
transpose = reshaped
print("Transpose array", transpose)


Transpose array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
arr1 = np.arange(16)
print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [51]:
reshaped = arr1.reshape((4,4))
print(" Reshape array:\n", reshaped)


flattened = reshaped.flatten()
print("flattened array", flattened)

raveled = reshaped.ravel()
print("raveled array",raveled)

transpose = reshaped
print("Transpose array\n", transpose)


 Reshape array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Transpose array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
